model:
  name: vit_b_16
  num_classes: 5

train:
  epochs: 100
  lr: 0.0005
  batch_size: 16
  num_workers: 4
  save_path: "./work_dirs"

data:
  root: "D:/Desktop/uie/data/flowers"  # 绝对路径：uie/data/flowers
  image_size: 224